<?php
/**
 * AspectRecommendationsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  eBay\Sell\Compliance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Compliance API
 *
 * Service for providing information to sellers about their listings being non-compliant, or at risk for becoming non-compliant, against eBay listing policies.
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eBay\Sell\Compliance\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AspectRecommendationsTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the aspectsRecommendation container, which is returned if eBay has found a listing with missing or invalid item aspects (ASPECTS_ADOPTION compliance type).
 * @package     eBay\Sell\Compliance
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AspectRecommendationsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AspectRecommendations"
     */
    public function testAspectRecommendations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "localized_aspect_name"
     */
    public function testPropertyLocalizedAspectName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "suggested_values"
     */
    public function testPropertySuggestedValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
